sequenceDiagram
    user->>faunus ui: notify me
    faunus ui->>firebase: get token
    firebase->>faunus ui: token
    faunus ui->>faunus api: register notification(token)
    faunus api->>faunus ui: ok
    faunus ui->>user: ok