spring:
  datasource:
    url: jdbc:h2:mem:plantdb;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enabled: true
server:
  address: 0.0.0.0
  port: 8080
firebase:
  config: ${FIREBASE_CONFIG}