# fly.toml app configuration file generated for faunus-ui on 2023-10-01T20:41:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "faunus-ui"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
