CREATE TABLE OWNER_PLANT (
    id SERIAL PRIMARY KEY,
    owner_id SERIAL NOT NULL,
    plant_id SERIAL NOT NULL
);

ALTER TABLE OWNER_PLANT ADD CONSTRAINT fk_owner_plant_owner
    FOREIGN KEY (owner_id) REFERENCES OWNER(id);

ALTER TABLE OWNER_PLANT ADD CONSTRAINT fk_owner_plant_plant
    FOREIGN KEY (plant_id) REFERENCES PLANT(id);